### ISSUE TITLE
cannot adjust height until appbar

### ISSUE THREAD

**Issue by rifal-klikeat** [gildaswise/rounded_modal#2]
hei can you add function so we can adjust modal height full to top of appbar

**Comment by gildaswise** [comment]
As this is just a "fork" from the original behaviour for the `showModalBottomSheet` method and I also want to keep by the Material Design guidelines on modals, that won't be done for this package.

There's some members on the [Flutter Dev Discord server](https://discord.gg/N7Yshp4) that were trying to do this implementation, I recommend asking around there.
