### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by frey1esm** [gildaswise/rounded_modal#4]
Is it possible to adjust animation speed? Easing?

Adjusting this line had no effect:

`Duration get transitionDuration => Duration(milliseconds: 200);`

**Comment by gildaswise** [comment]
`_RoundedBottomSheetState` controls the animation itself, along with `        BottomSheet.createAnimationController`, so from what I know, the animation speed/easing is defined by the framework, and you can overwrite that if needed but I want this package to be as close as the guidelines want.
