### ISSUE TITLE
unwanted padding added to the bottom

### ISSUE THREAD

**Issue by martipello** [gildaswise/rounded_modal#6]
using this rather than the standard bottom sheet there is unwanted padding added to the bottom of the sheet, i can't add screenshots due to commercial project but im sure youll be able to reproduce this, im using columns inside all set to mainAxisSize : MainAxisSize.min

**Comment by gildaswise** [comment]
Hey, using a Column with MainAxisSize.min results in this:

![Simulator Screen Shot - iPhone SE - 2019-04-02 at 18 19 09](https://user-images.githubusercontent.com/1339236/55436893-e00c1900-5573-11e9-8a2d-81f317610210.png)

So probably you have some padding on your widgets that's not really apparent; try using the Widget Inspector to find out where the padding might be! Remember that, for example, ListTile has a default horizontal padding of 16, and IconButton has all-around padding of 8.
