### ISSUE TITLE
Material

### ISSUE THREAD

**Issue by tomosullivan8** [gildaswise/rounded_modal#8]
Can you wrap the modal in a material with a type of transparent so when the InkWell splash effect is used it shows up?

Thanks!

**Comment by gildaswise** [comment]
Hey, Tom! I ran into this issue a few days ago and sadly just updating the Material on the modal didn't work; the fix is to involve the item that has the InkWell like this:

```dart
Material(
    child: Theme(
        data: Theme.of(context).copyWith(canvasColor: Colors.white),
        child: ???,
    ),
);
```

**Comment by tomosullivan8** [comment]
Hi, thanks for the reply, i managed to solve my issue by slightly adjusting like above but around the whole modal with the `type.MaterialTransparency`. 

Just so you know, the modal provided by the flutter package actually provides the `borderradius` now with the updated flutter package with various other updates such as background color etc. 

Thanks for providing the package though, has helped me out a lot previously!
